version: '3.8'
services:
  coffees-database:
    container_name: coffees-database
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - coffees-database:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  coffees-database: